# -*- coding: utf-8 -*-
"""__str del init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUV_4JKMzv0wqRwYSUnnldEH87eRstca
"""

class college():
  
  def __init__(self,clg,location,pincode,tier):
    self.clg=clg
    self.location=location
    self.pincode=pincode
    self.tier=tier
  
  def __str__(self):
    return f"this information is about {self.clg} college information......"
  
  def __del__(self):
    print("the instances of the object have been......")

  def display_info(self):
    if self.tier < 2:
      print("it is a tier one clg and it has gud placements")
    else:
      print("it is a decent clg and it has moderate placements")

obj=college("ksr","tiruchengodu",12345,2)

obj.display_info()

print(obj)

del(obj)

from traitlets.traitlets import Int
class college():
  
  def __init__(self):

    clg=(input("enter clg:"))
    location=(input("enter location:"))
    pincode=(input("enter pin:"))
    tier=(input("enter tier:"))
  
    self.clg=clg
    self.location=location
    self.pincode=pincode
    self.tier=tier
  
  def __str__(self):
    return f"this information is about {self.clg} college information......"
  
  def __del__(self):
    print("the instances of the object have been......")

  def display_info(self):
    
    if self.tier < 2:
      print("it is a tier one clg and it has gud placements")
    
    else:
      print("it is a decent clg and it has moderate placements")

obj=college()

del(obj)

