# -*- coding: utf-8 -*-
"""inheritance

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUV_4JKMzv0wqRwYSUnnldEH87eRstca
"""

class a:
  def func_A(self):
    print("printed a")
class b:  
  def func_B(self):
    print("printed b")
class c(b,a):
  def func_C(self):
    print("printed c")

obj=c()

c.mro()

obj.func_C()
obj.func_A()

class a:
  def function(self):
    print("printed a")

class b:  
  def function(self):
    print("printed b")

class c(b,a):
  def function(self):
    print("printed c")

obj1=c()

obj1.function()
c.mro()

obj1.function()

b.function(obj1)

class a:
  def function(self,name,year):
    print("printed a")
class b:  
  def function(self,name,year):
    #print(f"hi {self.name} after ten yrs yoy will be {2023-{self year}+10}")
class c(b,a):
  def function(self,name,year):
    self.name=name
    self.year=year
    age=2023-(self.year)  
    print(f"hi {self.name}, your age is {age}")

obj=c()

obj.function("aswin",2002)

class united_schools():
  def __init__(self,scl_name,scl_code,scl_address):
    self.scl_name=scl_name
    self.scl_code=scl_code
    self.scl_address=scl_address
  def show_school(self):
    print("school name=",self.scl_name)
    print("school code=",self.scl_code)
    print("school address=",self.scl_address)

class holy_cross_boys(united_schools):
  def __init__(self,scl_name,scl_code,scl_address,scl_strength,scl_rating):
    super().__init__(scl_name,scl_code,scl_address)
    self.scl_strength=scl_strength
    self.scl_rating=scl_rating
  def show_scl_holy_cross_boys(self):
    print("school name=",self.scl_name)
    print("school code=",self.scl_code)
    print("school address=",self.scl_address)
    print("scl strength=",self.scl_strength)
    print("rating=",self.scl_rating)